### ISSUE TITLE
Implement any/all search request filters

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#73] opened 2015-06-02 18:01 UTC
Right now the graph server does not actually honor any of the search request filters (like referenceSetId, or the sequence ranges for join ends, etc.). They are silently ignored.

The server should first start returning errors when these are specified but not honored, and ideally actually implement them all.

**Comment by macieksmuga** [comment] 2015-06-02 18:22
This is a duplicate of #56, but I like the more explicit description here, so I'll keep both around, and resolve them together when completed.

**Closed as completed** 2017-07-07 17:06 UTC
Labels: wontfix
